site_name: BetonQuest German
theme:
  palette:
    scheme: default

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: de
  font:
    text: Roboto
    code: Roboto Mono
